---
- name: "Installing Nginx and Doing the required updates"
  hosts: web1
  become: true
  tasks:
    - name: "Installing Nginx"
      apt:
        name: nginx
        state: present
      notify:
        - "Restart Nginx"

    - name: "Copying Index.html file"
      copy:
        src: ./index.html
        dest: /var/www/html/index.nginx-debian.html
      notify:
        - "Restart Nginx"

    - name: "Updating Default Nginx PORT"
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/sites-available/default
      notify:
        - "Restart Nginx"

    - name: "Starting Nginx Service"
      service:
        name: nginx
        state: started
  
  handlers:
    - name: "Restart Nginx"
      service:
        name: nginx
        state: restarted

    - name: "Start Nginx"
      service:
        name: nginx
        state: started

