- name: "Leaning Variables"
  hosts: web1
  vars_files:
    - "define_variable.yml"
  
  vars_prompt:
    - name: NAME
      prompt: "Your Name is"

  vars:
    software_name: "Nginx"
    software_version: "16.04" 

  tasks:
    - name: "Using DEBUG Module"
      debug:
        msg: "Hello Every One. {{ software_name }} verison is {{ software_version }}"

    - name: "Using DEBUG Module to Test Ansible OS Family"
      debug:
        msg: "Ansible IS Family is {{ ansible_os_family }}"
    
    - name: "Using Promt Variable"
      debug:
        msg: "Hello Everyone. My name is {{ NAME }}"

    - name: Print all available facts
      debug:
        var: ansible_facts
